### ISSUE TITLE
Improving documentation about using package options

### ISSUE THREAD

**Issue by matteoredaelli** [jimhester/knitrBootstrap#166]
I'd like to set dynamically the title of the document

can you show in the README/documentation how to set package options like bootstrap.title?

thanks in advance
Matteo

**Comment by janeshdev** [comment]
I was also trying to display the title of the document but doesn't seem to display it. I used the following as suggested by author but still doesn't display anything. 

```---
output:
  knitrBootstrap::bootstrap_document:
    title: "Test file"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
---```

**Comment by KrishnaPG** [comment]
Facing the same issue. The title is not getting displayed

**Comment by humburg** [comment]
Try setting the title at the top level. This works for me (at least with #68):

```yaml
title: "Test file"
output:
  knitrBootstrap::bootstrap_document:
    theme: amelia
    highlight: sunburst
```

This is documented in the development version: https://github.com/jimhester/knitrBootstrap/blob/rmarkdown_template/README.md
