### ISSUE TITLE
Title in YAML header

### ISSUE THREAD

**Issue by nachti** [jimhester/knitrBootstrap#173]
Trying to get a title using `title` in YAML (as described [here](https://github.com/jimhester/knitrBootstrap#yaml-front-matter)) is not successful -- I can't find the title anywhere (`rmarkdown::render('test.Rmd', 'knitrBootstrap::bootstrap_document')`).
```
---
output:
  knitrBootstrap::bootstrap_document:
    title: "Test file"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents.
```

If I use the following lines instead to knit a *standard* html document (`rmarkdown::render('$(FILE).Rmd', 'html_document')`), everything is fine:

```
---
title: "Test file"
author: "Gerhard Nachtmann"
date: '`r Sys.Date()`'
output:
  html_document:
    theme: united
    toc: yes
  pdf_document:
    toc: yes
  knitrBootstrap::bootstrap_document:
#    title: 'Test file' # does not work
    theme: 'readable' # boot_style
    highlight: 'google code' # code_style
---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents.
```

Do you know what's wrong there?
~g
