### ISSUE TITLE
Renders VERY narrow

### ISSUE THREAD

**Issue by fdepaolis** [jimhester/knitrBootstrap#198]
I have a problem when trying to render an HTML document with knitrBootstrap::bootstrap_document:
This is the YAML:
```
output:
  knitrBootstrap::bootstrap_document:
    title: "Title goes here"
    theme: Cosmo
    highlight: Google Code
    theme.chooser: FALSE
    highlight.chooser: FALSE
```

...the result is a VERY narrow document and I can make it wider...no matter what...have you seen that before? Any hints?
Thank you
