### ISSUE TITLE
Unable to hide code or output.

### ISSUE THREAD

**Issue by Black-Milk** [jimhester/knitrBootstrap#59]
I'm unable to specify the option to Hide Code or Output via the YAML Front-Matter as such:

```

---
output:
  knitrBootstrap::bootstrap_document:
    title: "Test file"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
    show.code: FALSE
    show.output: FALSE

---
```

Whereas before, with the CRAN release of knitrbootstrap, I was able to specify the following in my .Rprofile and it would work:

```
options(rstudio.markdownToHTML =
function(inputFile, outputFile) {
library(knitrBootstrap)
knit_bootstrap_md(input=inputFile, output=outputFile, chooser=c("boot", "code"), show_code=FALSE, show_output=FALSE)
}
)
```

where `show_code=FALSE`  and `show_output=FALSE` are specified. How do I address this issue?
